MNT: rerender
conda-forge/boost-cpp-feedstock pull request #129
Opened 2022-10-31 18:29 UTC by conda-forge-linter

Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #128.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #128

2022-10-31 18:29 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-10-31 18:36 UTC, jakirkham commented on conda-forge.yml
> +  - 1.78.x
xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3599

2022-10-31 18:37 UTC, jakirkham commented
@conda-forge-admin, please re-render

2022-10-31 18:58 UTC, isuruf requested changes
Same as https://github.com/conda-forge/boost-cpp-feedstock/pull/130#issuecomment-1297532047

2022-10-31 19:00 UTC, jakirkham commented
We need to at least include the updated migration branches. Can you please push that in a way that you are comfortable with?

2023-09-27 00:27 UTC, h-vetinari commented
We now have 1.82 and will migrate to that soon. All other changes need to happen on https://github.com/conda-forge/boost-feedstock now.

2023-09-27 00:27 UTC, closed without merging